-- ==========================================================
-- PETITE GIRL NAILS - SUPABASE DATABASE INITIALIZATION SCRIPT
-- (Clean Production: 5 Menu Layanan Terisi, Data Booking & PON Kosong)
-- ==========================================================

-- 1. Create table: bookings
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    services JSONB NOT NULL DEFAULT '[]'::jsonb,
    design_inspo TEXT,
    appointment_date TEXT NOT NULL,
    appointment_time TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    calendar_event_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create table: pon_orders (Press On Nails tracking)
CREATE TABLE IF NOT EXISTS public.pon_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    deadline TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ANTRI',
    notes TEXT,
    calendar_event_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Create table: services (Katalog Layanan & Harga Studio)
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Nail Art',
    estimated_duration_min INTEGER NOT NULL DEFAULT 60,
    price BIGINT NOT NULL DEFAULT 50000,
    description TEXT
);

-- 4. Create table: blocked_slots (Hari Libur & Tutup Slot)
CREATE TABLE IF NOT EXISTS public.blocked_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    time TEXT,
    reason TEXT NOT NULL DEFAULT 'Jadwal Libur Studio',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==========================================================
-- NONAKTIFKAN RLS (Agar web & admin lancar membaca dan menyimpan)
-- ==========================================================
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pon_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_slots DISABLE ROW LEVEL SECURITY;

-- ==========================================================
-- KOSONGKAN DATA LAMA BOOKINGS & PON (Mulai dari Nol)
-- ==========================================================
TRUNCATE TABLE public.bookings RESTART IDENTITY;
TRUNCATE TABLE public.pon_orders RESTART IDENTITY;
TRUNCATE TABLE public.blocked_slots RESTART IDENTITY;

-- ==========================================================
-- SEED 5 MENU LAYANAN STANDAR PETITE GIRL NAILS
-- ==========================================================
INSERT INTO public.services (id, name, category, estimated_duration_min, price, description)
VALUES 
    (1, 'Nail art di kuku asli', 'Nail Art', 90, 75000, 'Manicure lengkap, buffing, kutek gel base & motif nail art manis pada kuku asli.'),
    (2, 'Tambah extension', 'Extension', 60, 50000, 'Tambahan perpanjangan kuku (soft gel tip / polygel) yang kuat dan natural.'),
    (3, 'Remove ext', 'Removal', 45, 30000, 'Pelepasan extension kuku lama dengan aman tanpa merusak kuku asli.'),
    (4, 'Remove nail gel', 'Removal', 30, 20000, 'Pembersihan dan pelepasan kutek gel lama menggunakan soaking lembut.'),
    (5, 'Pasang press on nails', 'Press On', 40, 25000, 'Pemasangan kuku palsu (PON) custom dengan lem khusus yang tahan lama dan rapi.')
ON CONFLICT (id) DO UPDATE 
SET 
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    estimated_duration_min = EXCLUDED.estimated_duration_min,
    price = EXCLUDED.price,
    description = EXCLUDED.description;

-- Set auto-increment sequence
SELECT setval('public.services_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.services));
